
port: 4321
address: "0.0.0.0"
storage_path: "/some/path"
psw_secret: secret
db_mongo_uri: mongodb://localhost:27017
jwt_secret: secret
jwt_epoch: 1

# this is mostly for manual testing
cors_allowed_hosts:
  - "http://localhost"


client_static_path: "/some/path"
_login_rate_limit: 5 # per ip # per hour